apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-emsapp
  namespace: app-dev
  labels:
    name: node-emsapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: node-emsapp
    spec:
      containers:
      - image: abhishekbadwaik/node-ems-k8s 
        name: node-emsapp
        ports:
        - containerPort: 5000



apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: app-prod
  labels:
    app: jenkins-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins
        image: jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
	- containerPort: 50000
