kind: Service
apiVersion: v1
metadata:
  labels:
    app: node-emsapp-service
  name: node-emsapp-service
spec:
  type: NodePort
  ports:
  - port: 8083
    nodePort: 30300
    targetPort: 5000
  selector:
    app: node-emsapp
