apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
  namespace: default
data:
  driver.classname: com.mysql.jdbc.Driver
  database.url: jdbc:mysql://mysql-svc.default:3306/test
  db.user: root
  db.password: admin
  dia.let: org.hibernate.dialect.MySQLDialect
