# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: mongologin
  labels:
    app: mongologin
spec:
  ports:
  - port: 80
    name: web
  # *.nginx.default.svc.cluster.local
  clusterIP: None
  selector:
    app: mongologin
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: web
spec:
  serviceName: "mongologin"
  replicas: 2
  template:
    metadata:
      labels:
        app: mongologin
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mongologin
        image: abhishekbadwaik/db_login_api_v1
        ports:
        - containerPort: 27017
          name: web
        volumeMounts:
        - name: glusterfsvol
          mountPath: /data/db
      volumes:
      - name: glusterfsvol
        persistentVolumeClaim:
          claimName: gluster-claim 
