apiVersion: v1
kind: Pod
metadata:
  name: jenkins-ebs
  namespace: app-dev
  labels:
    app: jenkins-app
spec:
  containers:
  - image: jenkins
    name: jenkins
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /jenkins


apiVersion: v1
kind: Pod
metadata:
  name: test-hostpath
spec:
  containers:
  - image: myimage
    name: test-container
    volumeMounts:
    - mountPath: /test-hostpath
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /path/to/my/dir
